<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <NoWarn>$(NoWarn);OPENAI001;MAAI001</NoWarn>
    <DefaultItemExcludes>$(DefaultItemExcludes);**\out\**;**\.local\**</DefaultItemExcludes>
  </PropertyGroup>
</Project>
